//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.loans = new HashSet<loan>();
            this.sms = new HashSet<sm>();
        }
        
        public virtual area area { get; set; }
        public virtual ICollection<loan> loans { get; set; }
        public virtual ICollection<sm> sms { get; set; }
    }
}
