//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string ID_TYPE { get; set; }
        public string ID_NUM { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime DOB { get; set; }
        public string GENDER { get; set; }
        public string NATIONALITY { get; set; }
        public string CIVIL_STATUS { get; set; }
        public byte[] PROFPIC { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_HP1 { get; set; }
        public string PHONE_HP2 { get; set; }
        public string PHONE_RECIDENCE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ISRESIGN { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> INSERT_USER_ID { get; set; }
        public Nullable<int> UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATETIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string RELIGION { get; set; }
    }
}
