//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagementSystem.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class loandbEntities : DbContext
    {
        public loandbEntities()
            : base("name=loandbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<branch> branches { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<employee_cash> employee_cash { get; set; }
        public DbSet<loan> loans { get; set; }
        public DbSet<loan_type> loan_type { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<sm> sms { get; set; }
    }
}
